name: polkawallet_plugin_zeitgeist
description: The zeitgeist network flutter plugin for polkawallet app.
version: 0.3.7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  polkawallet_sdk: ^0.4.7
  polkawallet_ui: ^0.4.7

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^4.1.4

dependency_overrides:
  polkawallet_ui:
    path: ../ui
  polkawallet_sdk:
    path: ../sdk

flutter:
  assets:
    - assets/images/public/
    - assets/images/tokens/
